datamysql:
  extends:
    file: ./.docker-compose-common.yml
    service: datamysql

datadrupal:
  extends:
    file: ./.docker-compose-common.yml
    service: datadrupal

mysql:
  extends:
    file: ./.docker-compose-common.yml
    service: mysql
  volumes_from:
    - datamysql

drupal:
  extends:
    file: ./.docker-compose-common.yml
    service: drupal
  environment:
    - BUILD_TEST=1
  volumes_from:
    - datadrupal
  links:
    - mysql:mysql
